// <auto-generated />
namespace Calculator.Service.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SetAutomaticGenerationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetAutomaticGenerationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201904290939201_SetAutomaticGenerationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
